### ISSUE TITLE
More rust versions

### ISSUE THREAD

**Issue by wahjava** [declantsien/guix-rustup#1]
Hi!

Just wondering if there are plans to update this channel with new version of Rust ?

Let me know if there is something I can help with.

Thanks!

**Comment by declantsien** [comment]
Have you tried `guix build -e '((@@ (rustup build toolchain) rustup) "stable-1.79.0")'` or `guix build -e '((@@ (rustup build toolchain) rustup) "stable-2024-06-13")'` for `1.79.0` version.

**Comment by declantsien** [comment]
Thanks for this report.
I've added 1.79.0. Also fixed `guix build -e '((@@ (rustup build toolchain) rustup) "stable-1.79.0")'`
Search result from guix command line are some pre-downloaded manifests using default profile`(cargo clippy rust-docs rust-mingw rust-std rustc rustfmt)`.

You may want to try `rustup` procedure directly in your `manifest.scm` or `guix.scm`. Since it's more powerful and it can pull the latest rust versions.
